### ISSUE TITLE
请问项目引用的一些dll开源没有

### ISSUE THREAD

**Issue by tiger2014** [xin-lai/Magicodes.WeChat.SDK#8]
比如：
Magicodes.WeChat.SDK.Core
Magicodes.WeiChat.ComponentModel
Magicodes.WeiChat.Data
d等等
![image](https://user-images.githubusercontent.com/6703612/50647591-ecec9100-0fb3-11e9-9883-4b51f3a446a4.png)

**Comment by xin-lai** [comment]
![image](https://user-images.githubusercontent.com/22255486/61504417-d8cb2700-aa0d-11e9-9198-363cd6345c9f.png)
